name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['**/*.rb', '**/*.yml', '**/*.lock', '**/*.gemspec']
  push:
    branches:
      - master
    paths: ['**/*.rb', '**/*.yml', '**/*.lock', '**/*.gemspec']

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  parsec-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby: ['2.5.5', '2.7.7', '2.7.8', '3.0.6', '3.1.4', '3.2.2']

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v1


      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Gems
        id: gems
        run: |
          bundle install -j 5

      - name: Build
        id: build
        run: |
          gem build parsec.gemspec
          gem install ./parsecs-*.gem --verbose

      - name: Tests
        id: tests
        run: |
          ruby -Ilib -Iext/libnativemath test/test_parsec.rb
